import { test, expect } from "@playwright/test";
import path from "node:path";

test.beforeEach(async ({ page }) => {
  await page.goto("/");
  await expect(page.locator(".book-card")).toHaveCount(6);
});

test("imports a real PDF, renders pages, bookmarks, and resumes after reload", async ({ page }) => {
  const errors: string[] = [];
  const outgoingRequests: { url: string; method: string }[] = [];
  page.on("pageerror", error => errors.push(error.message));
  page.on("request", request => outgoingRequests.push({ url: request.url(), method: request.method() }));
  await page.locator('input[type="file"]').setInputFiles(path.resolve("public/demo/noticing.pdf"));
  await expect(page.locator(".book-card")).toHaveCount(7);
  await page.locator(".book-card").first().getByRole("button", { name: "Read The Art of Noticing" }).click();
  await expect(page.locator(".reader canvas")).toBeVisible();
  await page.getByRole("button", { name: "Next page", exact: true }).click();
  await expect(page.locator(".reader canvas")).toHaveAttribute("aria-label", /Page 2 of 7/);
  await expect(page.locator(".reader canvas")).toBeVisible();
  await page.keyboard.press("ArrowRight");
  await expect(page.locator(".reader canvas")).toHaveAttribute("aria-label", /Page 3 of 7/);
  await page.keyboard.press("ArrowLeft");
  await expect(page.locator(".reader canvas")).toHaveAttribute("aria-label", /Page 2 of 7/);
  await expect(page.locator(".reader canvas")).toBeVisible();
  await page.getByRole("button", { name: "Bookmark this page" }).click();
  await expect(page.getByRole("button", { name: "Remove bookmark", exact: true })).toBeVisible();
  await page.getByRole("slider", { name: "Reading progress" }).fill("5");
  await expect(page.locator(".reader canvas")).toBeVisible();
  await page.getByRole("button", { name: "1 bookmark", exact: true }).click();
  await page.getByRole("button", { name: "Page 2", exact: true }).click();
  await expect(page.locator(".reader canvas")).toHaveAttribute("aria-label", /Page 2 of 7/);
  await expect(page.locator(".reader canvas")).toBeVisible();
  await page.getByRole("button", { name: "Back to library" }).click();
  await expect(page.locator(".book-card").first()).toContainText("29% read");
  await page.reload();
  await expect(page.locator(".book-card")).toHaveCount(7);
  await page.getByRole("button", { name: "Continue reading", exact: true }).click();
  await expect(page.locator(".reader canvas")).toHaveAttribute("aria-label", /Page 2 of 7/);
  await expect(page.getByRole("button", { name: "Remove bookmark", exact: true })).toBeVisible();
  await expect(page.locator(".reader canvas")).toBeVisible();
  await page.getByRole("button", { name: "1 bookmark", exact: true }).click();
  await page.getByRole("button", { name: "Delete bookmark on page 2" }).click();
  await expect(page.getByText("Save a page for later.", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Close panel" }).click();
  await expect(page.getByRole("button", { name: "Bookmark this page" })).toBeVisible();
  expect(errors).toEqual([]);
  expect(outgoingRequests.filter(request => request.url.startsWith("http") && (!request.url.startsWith("http://localhost:3000/") || request.method !== "GET"))).toEqual([]);
});

test("organizes books, persists appearance, and removes local copies", async ({ page }) => {
  await page.locator(".book-card").first().getByRole("button", { name: "Favorite The Art of Noticing", exact: true }).click();
  await page.getByRole("group", { name: "Filter library" }).getByRole("button", { name: "Favorites", exact: true }).click();
  await expect(page.locator(".book-card")).toHaveCount(1);
  await page.getByRole("button", { name: "Options for The Art of Noticing" }).click();
  await page.getByRole("button", { name: "Rename", exact: true }).click();
  await page.getByLabel("Book title").fill("A Book of Small Wonders");
  await page.getByRole("button", { name: "Save name" }).click();
  await expect(page.locator(".book-card")).toContainText("A Book of Small Wonders");
  await page.getByRole("button", { name: "Create collection", exact: true }).click();
  await page.getByLabel("Collection name").fill("Weekend reads");
  await page.getByRole("button", { name: "Create collection", exact: true }).last().click();
  await page.getByRole("button", { name: "Options for A Book of Small Wonders" }).click();
  await page.getByRole("button", { name: "Add to collection", exact: true }).click();
  await page.getByRole("button", { name: "Weekend reads", exact: true }).click();
  await page.getByRole("button", { name: "All done" }).click();
  await page.getByRole("navigation", { name: "Collections", exact: true }).getByRole("button", { name: /Weekend reads/ }).click();
  await expect(page.locator(".book-card")).toHaveCount(1);
  await page.getByRole("button", { name: "Open settings", exact: true }).click();
  await page.getByRole("button", { name: "Dark", exact: true }).click();
  await page.getByRole("button", { name: "Close panel" }).click();
  await page.reload();
  await expect(page.locator("html")).toHaveAttribute("data-theme", "dark");
  await page.getByRole("button", { name: "List view" }).click();
  await expect(page.locator(".book-grid")).toHaveClass(/book-list/);
  await page.getByRole("textbox", { name: "Search books" }).fill("Weekend reads");
  await expect(page.locator(".book-card")).toHaveCount(1);
  await page.getByRole("button", { name: "Options for A Book of Small Wonders" }).click();
  await page.getByRole("button", { name: "Book information" }).click();
  await expect(page.locator(".book-details")).toContainText("noticing.pdf");
  await page.getByRole("button", { name: "Remove book", exact: true }).click();
  await page.getByRole("button", { name: "Remove book", exact: true }).click();
  await expect(page.locator(".book-card")).toHaveCount(0);
  await page.getByRole("button", { name: "Clear search", exact: true }).first().click();
  await expect(page.locator(".book-card")).toHaveCount(5);
});

test("mobile swipes, center taps, page boundaries, zoom panning and completion", async ({ browser }) => {
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 2 });
  const page = await context.newPage();
  await page.goto("/");
  await expect(page.locator(".book-card")).toHaveCount(6);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  await expect(page.locator(".book-card").last()).toHaveCSS("opacity", "1");
  await page.screenshot({ path: "test-results/folio-mobile.png", fullPage: true });
  await page.getByRole("button", { name: "Start reading", exact: true }).click();
  await expect(page.locator(".reader canvas")).toBeVisible();
  await expect(page.getByRole("button", { name: "Previous page", exact: true })).toBeDisabled();
  const stage = await page.locator(".reader-stage").boundingBox();
  if (!stage) throw new Error("Missing reader stage");
  const y = stage.y + stage.height / 2;
  const cdp = await context.newCDPSession(page);
  const touch = async (type: "touchStart" | "touchMove" | "touchEnd", points: { x: number; y: number; id: number }[]) => cdp.send("Input.dispatchTouchEvent", { type, touchPoints: points });
  await touch("touchStart", [{ x: 315, y, id: 1 }]);
  await touch("touchMove", [{ x: 80, y, id: 1 }]);
  await touch("touchEnd", []);
  await expect(page.locator(".reader canvas")).toHaveAttribute("aria-label", /Page 2 of 7/);
  await expect(page.locator(".reader canvas")).toBeVisible();
  await page.touchscreen.tap(195, y);
  await expect(page.locator(".reader")).toHaveClass(/immersive/);
  await page.touchscreen.tap(195, y);
  await expect(page.locator(".reader")).not.toHaveClass(/immersive/);
  await touch("touchStart", [{ x: 150, y, id: 1 }, { x: 240, y, id: 2 }]);
  await touch("touchMove", [{ x: 80, y, id: 1 }, { x: 310, y, id: 2 }]);
  await touch("touchEnd", []);
  await expect(page.locator(".reader-stage")).toHaveClass(/is-zoomed/);
  await touch("touchStart", [{ x: 310, y, id: 1 }]);
  await touch("touchMove", [{ x: 85, y, id: 1 }]);
  await touch("touchEnd", []);
  await expect(page.locator(".reader canvas")).toHaveAttribute("aria-label", /Page 2 of 7/);
  await page.getByRole("button", { name: /Reset/ }).click();
  await page.getByRole("slider", { name: "Reading progress" }).fill("7");
  await expect(page.locator(".reader canvas")).toBeVisible();
  await expect(page.getByRole("button", { name: "Next page", exact: true })).toBeDisabled();
  await page.getByRole("button", { name: "Back to library" }).click();
  await page.getByRole("group", { name: "Filter library" }).getByRole("button", { name: "Finished", exact: true }).click();
  await expect(page.locator(".book-card")).toHaveCount(1);
  await page.locator(".book-card .book-open").scrollIntoViewIfNeeded();
  const cover = await page.locator(".book-card .book-open").boundingBox();
  if (!cover) throw new Error("Missing book cover");
  await touch("touchStart", [{ x: cover.x + cover.width / 2, y: cover.y + cover.height / 2, id: 1 }]);
  await page.waitForTimeout(650); // Hold long enough to exercise the long-press gesture.
  await touch("touchEnd", []);
  await expect(page.getByRole("button", { name: "Open book", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Close panel" }).click();
  await context.close();
});

test("installed shell and local PDFs remain usable offline", async ({ page, context }) => {
  await expect(page.getByText("Ready for offline reading", { exact: true })).toBeVisible({ timeout: 60000 });
  await page.evaluate(() => navigator.serviceWorker.ready.then(() => true));
  await context.setOffline(true);
  await page.reload();
  await expect(page.locator(".book-card")).toHaveCount(6);
  await page.getByRole("button", { name: "Start reading", exact: true }).click();
  await expect(page.locator(".reader canvas")).toBeVisible();
  await page.getByRole("button", { name: "Next page", exact: true }).click();
  await expect(page.locator(".reader canvas")).toHaveAttribute("aria-label", /Page 2 of 7/);
  await expect(page.locator(".reader canvas")).toBeVisible();
  await page.getByRole("button", { name: "Back to library" }).click();
  await page.locator('input[type="file"]').setInputFiles(path.resolve("public/demo/morning.pdf"));
  await expect(page.locator(".book-card")).toHaveCount(7);
});

test("rejects invalid PDFs without adding a broken book and renders desktop library", async ({ page }) => {
  await expect(page.locator(".book-card").last()).toHaveCSS("opacity", "1");
  await page.screenshot({ path: "test-results/folio-desktop.png", fullPage: true });
  await page.locator('input[type="file"]').setInputFiles({ name: "broken.pdf", mimeType: "application/pdf", buffer: Buffer.from("this is not a PDF") });
  await expect(page.locator(".toast[role='alert']")).toContainText("isn’t a readable PDF");
  await expect(page.locator(".book-card")).toHaveCount(6);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
});
